feat: regenerated
etclabscore/open-rpc-ethereum-js pull request #16
Opened 2019-03-21 00:18 UTC by BelfordZ

2019-03-21 00:24 UTC, BelfordZ commented on package.json
> +  "name": "template-client",
```suggestion
  "name": "@multi-geth/rpc-client",
```

2019-03-21 00:31 UTC, BelfordZ commented on package.json
>    "version": "1.0.0",
```suggestion
  "version": "1.0.1",
```

2019-03-21 00:54 UTC, shanejonas commented on docs/.nojekyll
> -
we need this

2019-03-21 23:53 UTC, shanejonas requested changes
dont delete `docs/.nojekyll`

2019-03-22 06:46 UTC, BelfordZ commented on docs/.nojekyll
> -
non scripted client - 100
us - 0

2019-04-03 15:46 UTC, closed without merging